/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.ManageAirliners;

import Buisness.Airliner;
import Buisness.AirlinerDirectory;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author gadep
 */
public class CreateNewAirlinerJPanel extends javax.swing.JPanel {
private JPanel userProcesContainer ;
 private Airliner travelagency;
 private AirlinerDirectory airDir;
    /**
     * Creates new form CreateManageTravelJPanel
     */
    public CreateNewAirlinerJPanel(JPanel userProcesContainer, AirlinerDirectory airDir) {
        initComponents();
        this.userProcesContainer = userProcesContainer;
       // this.travelagency = travelagency;
        this.airDir = airDir;
        
    }

   

   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtSeatCapacity = new javax.swing.JTextField();
        createBtn = new javax.swing.JButton();
        Back = new javax.swing.JButton();
        txtAirlineType = new javax.swing.JComboBox();
        txtAirlineName = new javax.swing.JComboBox();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("Create Airline");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(305, 50, -1, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 19)); // NOI18N
        jLabel2.setText("Airline name");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 104, -1, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 19)); // NOI18N
        jLabel3.setText("Aircraft type");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 148, -1, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 19)); // NOI18N
        jLabel4.setText("Flight Number");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 200, -1, -1));
        add(txtSeatCapacity, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 190, 140, -1));

        createBtn.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        createBtn.setText("Create");
        createBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createBtnActionPerformed(evt);
            }
        });
        add(createBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 280, -1, -1));

        Back.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        Back.setText("Back");
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });
        add(Back, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 360, -1, -1));

        txtAirlineType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Airbus A2220", "Airbus A320", "Boeing737", "Bombardier CRJ200", "Airbus A380" }));
        add(txtAirlineType, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 150, -1, -1));

        txtAirlineName.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Emirates (EK)", "Qatar Airways (QR)", "British Airways (BA)", "Air France (AF)", "American Airlines (AA)", "Lufthansa (LS)" }));
        add(txtAirlineName, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 100, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void createBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createBtnActionPerformed
        // TODO add your handling code here:
        
        if(txtSeatCapacity.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(null , "Please add all the Mandatory fields!!");
        }
           try
           {
        
            Double.parseDouble(txtSeatCapacity.getText());
           // Integer.parseInt(txtAvailablity.getText());
           }
           catch(NumberFormatException e)
           {
               JOptionPane.showMessageDialog(null , "Please enter numeric values only"); 
               txtAirlineName.getSelectedItem();
                txtAirlineType.getSelectedItem();
                txtSeatCapacity.setText("");
               return;
           }
            
           Airliner airliner = airDir.addProduct();
            airliner.setAirlineName((String) txtAirlineName.getSelectedItem());
            airliner.setAirlineType((String) txtAirlineType.getSelectedItem());
            airliner.setSeatCapacity(Double.parseDouble(txtSeatCapacity.getText()));
           // prod.setDescription(txtDescription.getText());
           
            JOptionPane.showMessageDialog(null, "Airliner Created Successfully");
            txtAirlineName.getSelectedItem();
            txtAirlineType.setSelectedItem("");
            txtSeatCapacity.setText("");
            //txtDescription.setText("");
    }//GEN-LAST:event_createBtnActionPerformed

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        // TODO add your handling code here:
        userProcesContainer.remove(this);
        CardLayout layout = (CardLayout)userProcesContainer.getLayout();
        layout.previous(userProcesContainer);
    }//GEN-LAST:event_BackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back;
    private javax.swing.JButton createBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JComboBox txtAirlineName;
    private javax.swing.JComboBox txtAirlineType;
    private javax.swing.JTextField txtSeatCapacity;
    // End of variables declaration//GEN-END:variables
}
