/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.ManageAirliners;

import Buisness.Airliner;
import Buisness.AirlinerDirectory;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author gadep
 */

public class TravelJPanel extends javax.swing.JPanel {

    /**
     * Creates new form TravelJPanel
     */
     private JPanel userProcesContainer ;
    private Airliner travelagency;
     private AirlinerDirectory airDir;
     
    
    public TravelJPanel(JPanel userProcesContainer, AirlinerDirectory airDir) {
        initComponents();
        this.userProcesContainer = userProcesContainer;
       // this.travelagency = travelagency;
        this.airDir = airDir;
      
    }

    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        createBtn = new javax.swing.JButton();
        viewBtn = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        createBtn.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        createBtn.setText("Create Airline");
        createBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createBtnActionPerformed(evt);
            }
        });
        add(createBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(83, 61, 250, -1));

        viewBtn.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        viewBtn.setText("View Airline");
        viewBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewBtnActionPerformed(evt);
            }
        });
        add(viewBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 60, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void createBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createBtnActionPerformed
        // TODO add your handling code here:
       CreateNewAirlinerJPanel caPanel = new  CreateNewAirlinerJPanel(userProcesContainer , airDir);
       userProcesContainer.add("CreateAccountJPanel" ,caPanel );
       CardLayout layout = (CardLayout)userProcesContainer.getLayout();
       layout.next(userProcesContainer);
        
    }//GEN-LAST:event_createBtnActionPerformed

    private void viewBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewBtnActionPerformed
        // TODO add your handling code here:
       ViewNewAirlinerJPanel caPanel = new  ViewNewAirlinerJPanel(userProcesContainer ,travelagency ,airDir);
       userProcesContainer.add("ViewNewAirlinerJPanel" ,caPanel );
       CardLayout layout = (CardLayout)userProcesContainer.getLayout();
       layout.next(userProcesContainer);
        
    }//GEN-LAST:event_viewBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton createBtn;
    private javax.swing.JButton viewBtn;
    // End of variables declaration//GEN-END:variables
}
