/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.ManageAirliners;

import Buisness.Airliner;
import Buisness.AirlinerDirectory;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author gadep
 */
public class ViewPanel extends javax.swing.JPanel {

    private JPanel userProcesContainer ;
 private Airliner travelagency;
 private AirlinerDirectory airDir;
    /**
     * Creates new form ViewPanel
     */
    public ViewPanel(JPanel userProcesContainer, Airliner travelagency, AirlinerDirectory airDir) {
        initComponents();
        this.userProcesContainer = userProcesContainer;
        this.airDir = airDir;
        this.travelagency  = travelagency;
        txtAirlineName.setSelectedItem(travelagency.getAirlineName());
        txtAirlineType.setSelectedItem(travelagency.getAirlineType());
        jTextField4.setText(String.valueOf(travelagency.getSeatCapacity()));
        populatedetails();
    }

    
         private void populatedetails()
    {
        txtAirlineName.setSelectedItem(travelagency.getAirlineName());
        txtAirlineType.setSelectedItem(String.valueOf(travelagency.getAirlineType()));
        jTextField4.setText(String.valueOf(travelagency.getSeatCapacity()));

        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        savebtn = new javax.swing.JButton();
        updateBtn = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();
        txtAirlineName = new javax.swing.JComboBox();
        txtAirlineType = new javax.swing.JComboBox();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("View Airliner");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(223, 29, 189, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 19)); // NOI18N
        jLabel2.setText("Airliner Name");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 128, -1, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 19)); // NOI18N
        jLabel3.setText("Airliner Type");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 210, -1, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 19)); // NOI18N
        jLabel4.setText("Flight Number");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 311, -1, -1));
        add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(219, 307, 219, -1));

        savebtn.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        savebtn.setText("Save");
        savebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savebtnActionPerformed(evt);
            }
        });
        add(savebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 399, -1, -1));

        updateBtn.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        updateBtn.setText("Update");
        updateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBtnActionPerformed(evt);
            }
        });
        add(updateBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(208, 399, -1, -1));

        backBtn.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        backBtn.setText("Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });
        add(backBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(61, 561, -1, -1));

        txtAirlineName.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Emirates (EK)", "Qatar Airways (QR)", "British Airways (BA)", "Air France (AF)", "American Airlines (AA)", "Lufthansa (LS)" }));
        add(txtAirlineName, new org.netbeans.lib.awtextra.AbsoluteConstraints(219, 124, -1, -1));

        txtAirlineType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Airbus A2220", "Airbus A320", "Boeing737", "Bombardier CRJ200" }));
        add(txtAirlineType, new org.netbeans.lib.awtextra.AbsoluteConstraints(219, 210, 220, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        userProcesContainer.remove(this);
        CardLayout layout = (CardLayout)userProcesContainer.getLayout();
        layout.previous(userProcesContainer);
        
        
        Component[] components = userProcesContainer.getComponents();
       for(Component c : components){
           if(c instanceof ViewNewAirlinerJPanel){
               ViewNewAirlinerJPanel panel = (ViewNewAirlinerJPanel) c;
              panel.populate();
           
    }//GEN-LAST:event_backBtnActionPerformed
       }
    }
    private void updateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtnActionPerformed
        // TODO add your handling code here:
         txtAirlineName.setEditable(true);
            txtAirlineType.setEditable(true);
            jTextField4.setEditable(true);
            
            savebtn.setEnabled(true);
            updateBtn.setEnabled(false);
    }//GEN-LAST:event_updateBtnActionPerformed

    private void savebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savebtnActionPerformed
        // TODO add your handling code here:
         try
        {
            txtAirlineName.setEditable(false);
            txtAirlineType.setEditable(false);
            jTextField4.setEditable(false);
            
            savebtn.setEnabled(false);
            updateBtn.setEnabled(true);
        
        
        
            travelagency.setAirlineName((String) txtAirlineName.getSelectedItem());
            travelagency.setAirlineType((String) txtAirlineType.getSelectedItem());
            travelagency.setSeatCapacity(Integer.parseInt(jTextField4.getText()));
            
            
            JOptionPane.showMessageDialog(null, "Airliner updated successfully"); 
        }
        
        catch(NumberFormatException e)
           {
               JOptionPane.showMessageDialog(null , "Please enter numeric values only"); 
               return;
           }
        
        
    }//GEN-LAST:event_savebtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JButton savebtn;
    private javax.swing.JComboBox txtAirlineName;
    private javax.swing.JComboBox txtAirlineType;
    private javax.swing.JButton updateBtn;
    // End of variables declaration//GEN-END:variables
}
