/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserIterface.AirlinesManageFlightSchedule;

import Buisness.Airliner;
import Buisness.AirlinerDirectory;
import Buisness.FlightSchedule;
import Buisness.FlightScheduleDirectory;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author gadep
 */
public class ComboBoxJPanel extends javax.swing.JPanel {
    
       JPanel userProcesContainer ;
    private Airliner travelagency;
      AirlinerDirectory airDir;
      private FlightSchedule flightschedule;
    private FlightScheduleDirectory fliDir;

    /**
     * Creates new form ComboBoxJPanel
     */
    public ComboBoxJPanel(JPanel userProcesContainer, AirlinerDirectory airDir ,FlightScheduleDirectory fliDir ) {
        initComponents();
        this.userProcesContainer = userProcesContainer;
        this.travelagency = travelagency;
        this.airDir = airDir;
        this.fliDir = fliDir;
        this.flightschedule = flightschedule;
        
        airlinerComboBox1.removeAllItems();
       for(Airliner travelagenc : airDir.getProductDirectory()) {
           airlinerComboBox1.addItem(travelagenc);
    }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        findButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        airlinerComboBox1 = new javax.swing.JComboBox();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 19)); // NOI18N
        jLabel1.setText("Airliner Name");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, -1, 30));

        findButton1.setText("GO");
        findButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                findButton1ActionPerformed(evt);
            }
        });
        add(findButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 130, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("Airliner List");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 50, -1, -1));

        airlinerComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        airlinerComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                airlinerComboBox1ActionPerformed(evt);
            }
        });
        add(airlinerComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 130, 150, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void findButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_findButton1ActionPerformed
        // TODO add your handling code here:
        //for(Airliner a : airDir.getProductDirectory()) {
            
     //   }
         Airliner travelagency = (Airliner)airlinerComboBox1.getSelectedItem();
        ScheduleCreation swajp = new ScheduleCreation(userProcesContainer,airDir,travelagency,fliDir);
        userProcesContainer.add("ScheduleCreation",swajp);
        CardLayout layout = (CardLayout)userProcesContainer.getLayout();
        layout.next(userProcesContainer);
        
    }//GEN-LAST:event_findButton1ActionPerformed

    private void airlinerComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_airlinerComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_airlinerComboBox1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox airlinerComboBox1;
    private javax.swing.JButton findButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables

}
