/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserIterface.AirlinesManageFlightSchedule;

import Buisness.Airliner;
import Buisness.AirlinerDirectory;
import Buisness.FlightSchedule;

import Buisness.FlightScheduleDirectory;
import java.awt.CardLayout;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author gadep
 */
public class CreateScheduleJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateSchedule
     */
    private Airliner travelagency;
    private AirlinerDirectory airDir;
    private JPanel userProcesContainer ;
    private FlightScheduleDirectory flightdir;
   // private Object jTextField1;
  //  public CreateScheduleJPanel(JPanel userProcesContainer, AirlinerDirectory airDir, Airliner travelagency)
    public CreateScheduleJPanel(JPanel userProcesContainer, AirlinerDirectory airDir , Airliner travelagency,FlightScheduleDirectory fliDir)
    {
        initComponents();
        this.userProcesContainer = userProcesContainer;
       this.travelagency = travelagency;
        this.airDir = airDir;
       this.flightdir = new FlightScheduleDirectory();
        
       // txtAirlineType.setText(travelagency.getAirlineName());
       txtAirlineName.setText(travelagency.getAirlineName());
        txtAirlineType.setText(travelagency.getAirlineType());
        txtSeatCapacity.setText(String.valueOf(travelagency.getSeatCapacity()));
        txtAirlineType.setEnabled(false);
        txtSeatCapacity.setEnabled(false);
        txtAirlineName.setEditable(false);
        
    }
 /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtSeatCapacity = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtAirlineType = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Createbtn = new javax.swing.JButton();
        backbtn = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        txtTime = new javax.swing.JComboBox();
        daystxt = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        hourscombo = new javax.swing.JComboBox();
        minutecombo = new javax.swing.JComboBox();
        hourscombo1 = new javax.swing.JComboBox();
        minutecombo1 = new javax.swing.JComboBox();
        txtFrom = new javax.swing.JComboBox();
        txtTo = new javax.swing.JComboBox();
        jLabel9 = new javax.swing.JLabel();
        txtAirlineName = new javax.swing.JTextField();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("Create Flight Schedule");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 30, 300, -1));

        txtSeatCapacity.setEnabled(false);
        add(txtSeatCapacity, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 157, 140, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 19)); // NOI18N
        jLabel3.setText("Airline type");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 130, -1, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 19)); // NOI18N
        jLabel4.setText("Flight Number");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 163, -1, -1));

        txtAirlineType.setEditable(false);
        add(txtAirlineType, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 130, 140, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 19)); // NOI18N
        jLabel2.setText("From");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 218, 94, -1));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 19)); // NOI18N
        jLabel5.setText("To");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 268, 94, -1));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 19)); // NOI18N
        jLabel6.setText("Date of Journey");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 320, -1, -1));

        Createbtn.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        Createbtn.setText("Create");
        Createbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreatebtnActionPerformed(evt);
            }
        });
        add(Createbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 480, -1, -1));

        backbtn.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        backbtn.setText("Back");
        backbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backbtnActionPerformed(evt);
            }
        });
        add(backbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 480, -1, -1));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 19)); // NOI18N
        jLabel7.setText("Arrival Time");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 400, 110, -1));

        txtTime.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Month", "January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December" }));
        txtTime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTimeActionPerformed(evt);
            }
        });
        add(txtTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 320, 80, -1));

        daystxt.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Day", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        add(daystxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 320, 100, -1));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 19)); // NOI18N
        jLabel8.setText("Departure Time");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 360, 140, -1));

        hourscombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Nill", "00", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23" }));
        add(hourscombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 400, -1, -1));

        minutecombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Nill", "00", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46", "47", "48", "49", "50", "51", "52", "53", "54", "55", "56", "57", "58", "59" }));
        minutecombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minutecomboActionPerformed(evt);
            }
        });
        add(minutecombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 400, 60, -1));

        hourscombo1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Nill", "00", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23" }));
        add(hourscombo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 360, -1, -1));

        minutecombo1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Nill", "00", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46", "47", "48", "49", "50", "51", "52", "53", "54", "55", "56", "57", "58", "59" }));
        minutecombo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minutecombo1ActionPerformed(evt);
            }
        });
        add(minutecombo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 360, -1, -1));

        txtFrom.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "None", "New Jersey", "California", "Boston", "New Jersey" }));
        add(txtFrom, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 220, -1, -1));

        txtTo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "None", "Georgia", "New York", "Ohio", "Washington", "New Jersey" }));
        add(txtTo, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 260, -1, -1));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 19)); // NOI18N
        jLabel9.setText("Airliner name");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, -1, -1));

        txtAirlineName.setEnabled(false);
        add(txtAirlineName, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 100, 140, -1));

        jTextField1.setText("Hrs");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 400, 40, -1));

        jTextField2.setText("Mins");
        add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 400, -1, -1));

        jTextField3.setText("Hrs");
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 360, 40, -1));

        jTextField4.setText("Mins");
        add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 360, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void CreatebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreatebtnActionPerformed
        // TODO add your handling code here:
       /*  if(txtFrom.getSelectedItem().isEmpty() || txtTo.getSelectedItem().isEmpty() || txtTime.getSelectedItem().isEmpty())
        {
             JOptionPane.showMessageDialog(null , "Please add all the Mandatory fields!!");
        }*/
           String.valueOf(txtFrom.getSelectedItem());
             String.valueOf(txtTo.getSelectedItem());
             String.valueOf(txtTime.getSelectedItem());
             
             String.valueOf(daystxt.getSelectedItem());
             String.valueOf(hourscombo1.getSelectedItem());
             String.valueOf(minutecombo1.getSelectedItem());
             String.valueOf(hourscombo.getSelectedItem());
              String.valueOf(minutecombo.getSelectedItem());
             
           if(txtFrom.getSelectedItem() == txtTo.getSelectedItem())
           {
               JOptionPane.showMessageDialog(null, "Destination and Source can't be the same,Sorry ! Please re-enter");
               return;
             //   txtFrom.setSelectedIndex(0);
              //  txtTo.setSelectedIndex(0);
             //  clearFields();
               
           }
           
           if(txtTime.getSelectedItem() == "Month" || daystxt.getSelectedItem() == "Day")
           {
             JOptionPane.showMessageDialog(null, "Please enter Date of Journey details");
               return;  
           }
          if(hourscombo1.getSelectedItem() == "Nill" || minutecombo1.getSelectedItem() == "Nill")
           {
             JOptionPane.showMessageDialog(null, "Please enter Departure time details");
               return;  
           }
          
           if(hourscombo1.getSelectedItem() == "00" || minutecombo1.getSelectedItem() == "00")
           {
             JOptionPane.showMessageDialog(null, "Please enter  correct Departure time details");
               return;  
           }
            
          if(hourscombo.getSelectedItem() == "Nill" || minutecombo.getSelectedItem() == "Nill")
           {
             JOptionPane.showMessageDialog(null, "Please enter Arrival time details");
               return;  
           }
          
          if(hourscombo.getSelectedItem() == "00" || minutecombo.getSelectedItem() == "00")
           {
             JOptionPane.showMessageDialog(null, "Please enter correct Arrival time details");
               return;  
           }
           
           if(String.valueOf(txtTime.getItemAt(txtTime.getSelectedIndex())).equals("February") && Integer.parseInt(String.valueOf(daystxt.getItemAt(daystxt.getSelectedIndex()))) > 28 )
           {
               JOptionPane.showMessageDialog(null, "February does not have the day u entered,Please re-enter");
               return;
           }
           
            if(String.valueOf(txtTime.getItemAt(txtTime.getSelectedIndex())).equals("April") && Integer.parseInt(String.valueOf(daystxt.getItemAt(daystxt.getSelectedIndex()))) > 30 )
           {
               JOptionPane.showMessageDialog(null, "April does not have the day u entered,Please re-enter");
               return;
           }
            
            if(String.valueOf(txtTime.getItemAt(txtTime.getSelectedIndex())).equals("June") && Integer.parseInt(String.valueOf(daystxt.getItemAt(daystxt.getSelectedIndex()))) > 30 )
           {
               JOptionPane.showMessageDialog(null, "June does not have the day u entered,Please re-enter");
               return;
           }
            
            if(String.valueOf(txtTime.getItemAt(txtTime.getSelectedIndex())).equals("June") && Integer.parseInt(String.valueOf(daystxt.getItemAt(daystxt.getSelectedIndex()))) > 30 )
           {
               JOptionPane.showMessageDialog(null, "June does not have the day u entered,Please re-enter");
               return;
           }
            
            if(String.valueOf(txtTime.getItemAt(txtTime.getSelectedIndex())).equals("September") && Integer.parseInt(String.valueOf(daystxt.getItemAt(daystxt.getSelectedIndex()))) > 30 )
           {
               JOptionPane.showMessageDialog(null, "June does not have the day u entered,Please re-enter");
               return;
           }
            
           if(String.valueOf(txtTime.getItemAt(txtTime.getSelectedIndex())).equals("November") && Integer.parseInt(String.valueOf(daystxt.getItemAt(daystxt.getSelectedIndex()))) > 30 )
           {
               JOptionPane.showMessageDialog(null, "June does not have the day u entered,Please re-enter");
               return;
           } 
            
            FlightSchedule flightobj = this.flightdir.addProduct();
           
            txtAirlineName.getText();
            txtAirlineType.getText();
            txtSeatCapacity.getText();
            flightobj.setFrom((String) txtFrom.getSelectedItem());
            flightobj.setTo((String) txtTo.getSelectedItem());
            flightobj.setDateofJourney(txtTime.getSelectedItem().toString() +"/" +  daystxt.getSelectedItem().toString());
            flightobj.setDepartureTime(hourscombo1.getSelectedItem().toString() + "/" +  minutecombo1.getSelectedItem().toString());
            flightobj.setArrivalTime(hourscombo.getSelectedItem().toString() + "/" +  minutecombo.getSelectedItem().toString());
            travelagency.setFlightScheduleDirectory(flightdir);
          
           
            JOptionPane.showMessageDialog(null, "Airliner Created Successfully");
            clearFields();
          
    }//GEN-LAST:event_CreatebtnActionPerformed
private void clearFields()
{
    txtFrom.setSelectedIndex(0);
    txtTo.setSelectedIndex(0);
    txtTime.setSelectedIndex(0);
    daystxt.setSelectedIndex(0);
    hourscombo1.setSelectedIndex(0);
    hourscombo.setSelectedIndex(0);
    minutecombo1.setSelectedIndex(0);
    minutecombo.setSelectedIndex(0);
}
    private void backbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbtnActionPerformed
        // TODO add your handling code here:
        userProcesContainer.remove(this);
        CardLayout layout = (CardLayout)userProcesContainer.getLayout();
        layout.previous(userProcesContainer);
    }//GEN-LAST:event_backbtnActionPerformed

    private void minutecomboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minutecomboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_minutecomboActionPerformed

    private void minutecombo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minutecombo1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_minutecombo1ActionPerformed

    private void txtTimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTimeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTimeActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Createbtn;
    private javax.swing.JButton backbtn;
    private javax.swing.JComboBox daystxt;
    private javax.swing.JComboBox hourscombo;
    private javax.swing.JComboBox hourscombo1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JComboBox minutecombo;
    private javax.swing.JComboBox minutecombo1;
    private javax.swing.JTextField txtAirlineName;
    private javax.swing.JTextField txtAirlineType;
    private javax.swing.JComboBox txtFrom;
    private javax.swing.JTextField txtSeatCapacity;
    private javax.swing.JComboBox txtTime;
    private javax.swing.JComboBox txtTo;
    // End of variables declaration//GEN-END:variables
}
