/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserIterface.AirlinesManageFlightSchedule;

import Buisness.Airliner;
import Buisness.AirlinerDirectory;
import Buisness.FlightSchedule;
import Buisness.FlightScheduleDirectory;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author gadep
 */
public class ScheduleCreation extends javax.swing.JPanel {

    /**
     * Creates new form ScheduleCreation
     */
    
    private JPanel userProcesContainer ;
    private Airliner travelagency;
    private AirlinerDirectory airDir;
    private FlightSchedule flightschedule;
    private FlightScheduleDirectory fliDir;
    //public ScheduleCreation(JPanel userProcesContainer, AirlinerDirectory airDir, Airliner travelagency)
     public ScheduleCreation(JPanel userProcesContainer, AirlinerDirectory airDir, Airliner travelagency,FlightScheduleDirectory fliDir){
        initComponents();
        this.userProcesContainer = userProcesContainer;
        this.travelagency = travelagency;
        this.airDir = airDir;
        this.fliDir = fliDir;
       // this.flightschedule = flightschedule;
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        createSchedule = new javax.swing.JButton();
        viewSchedule = new javax.swing.JButton();
        backbtn = new javax.swing.JButton();

        createSchedule.setFont(new java.awt.Font("Times New Roman", 1, 21)); // NOI18N
        createSchedule.setText("Create Schedule");
        createSchedule.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createScheduleActionPerformed(evt);
            }
        });

        viewSchedule.setFont(new java.awt.Font("Times New Roman", 1, 21)); // NOI18N
        viewSchedule.setText("View Schedule");
        viewSchedule.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewScheduleActionPerformed(evt);
            }
        });

        backbtn.setFont(new java.awt.Font("Times New Roman", 1, 21)); // NOI18N
        backbtn.setText("Back");
        backbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(backbtn)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(createSchedule)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                        .addComponent(viewSchedule)
                        .addGap(109, 109, 109))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(createSchedule)
                    .addComponent(viewSchedule))
                .addGap(101, 101, 101)
                .addComponent(backbtn)
                .addContainerGap(129, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void createScheduleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createScheduleActionPerformed
        // TODO add your handling code here:
        CreateScheduleJPanel mpcjp = new CreateScheduleJPanel(userProcesContainer,airDir ,travelagency,fliDir);
        userProcesContainer.add("ManageProductCatalogJPanel",mpcjp);
        CardLayout layout = (CardLayout)userProcesContainer.getLayout();
        layout.next(userProcesContainer);
        
    }//GEN-LAST:event_createScheduleActionPerformed

    private void viewScheduleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewScheduleActionPerformed
        // TODO add your handling code here:
        ViewFlightSchedule mpcjp = new ViewFlightSchedule(userProcesContainer, airDir , travelagency  );
        userProcesContainer.add("ViewScheduleJPanel",mpcjp);
        CardLayout layout = (CardLayout)userProcesContainer.getLayout();
        layout.next(userProcesContainer);
    }//GEN-LAST:event_viewScheduleActionPerformed

    private void backbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbtnActionPerformed
        // TODO add your handling code here:
        userProcesContainer.remove(this);
        CardLayout layout = (CardLayout)userProcesContainer.getLayout();
        layout.previous(userProcesContainer);
    }//GEN-LAST:event_backbtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backbtn;
    private javax.swing.JButton createSchedule;
    private javax.swing.JButton viewSchedule;
    // End of variables declaration//GEN-END:variables
}
