/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserIterface.AirlinesManageFlightSchedule;

import Buisness.Airliner;
import Buisness.AirlinerDirectory;
import Buisness.FlightSchedule;
import Buisness.FlightScheduleDirectory;
import UserInterface.ManageAirliners.ViewPanel;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author gadep
 */
public class ViewFlightSchedule extends javax.swing.JPanel {

    /**
     * Creates new form ViewFlightSchedule
     */
    private JPanel userProcesContainer ;
    private Airliner travelagency;
     private AirlinerDirectory airDir;
     private FlightSchedule flightschedule;
     private FlightScheduleDirectory flightdir;
    public ViewFlightSchedule(JPanel userProcesContainer, AirlinerDirectory airDir, Airliner travelagency ) {
        initComponents();
        this.userProcesContainer = userProcesContainer;
        this.airDir = airDir;
       this.travelagency = travelagency;
        this.flightschedule = flightschedule;
        this.flightdir = flightdir;
        populateTable();
       
    }

    
    public void populateTable()
   {
        DefaultTableModel dtm =  (DefaultTableModel)tblDirectory.getModel();
        dtm.setRowCount(0);
       for(Airliner a : airDir.getProductDirectory()){
          {
               for(FlightSchedule ars: a.getFlightScheduleDirectory().getSDListS())
            {
           Object row[] = new Object[dtm.getColumnCount()]; 
         //  row[0] = travelagency.getAirlineName();
           row[0] = a;
           row[1] = a.getAirlineType();
           row[2] = a.getSeatCapacity();
           
                
           row[3] = ars.getFrom();
           row[4] = ars.getTo();
           row[5] = ars.getDateofJourney();
           row[6] = ars.getDepartureTime();
           row[7] = ars.getArrivalTime();
          
           dtm.addRow(row);
           
        }
          }

    }
    }
  /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        DeleteAirline = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDirectory = new javax.swing.JTable();
        backBtn = new javax.swing.JButton();
        txtView = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 25)); // NOI18N
        jLabel1.setText("View Flight Scedule");

        DeleteAirline.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        DeleteAirline.setText("Delete Airline");
        DeleteAirline.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteAirlineActionPerformed(evt);
            }
        });

        tblDirectory.setFont(new java.awt.Font("Times New Roman", 1, 21)); // NOI18N
        tblDirectory.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Airlinername", "AirlinerType", "Flight number", "From", "To", "Date of Journey", "DepartureTime", "ArrivalTime"
            }
        ));
        jScrollPane1.setViewportView(tblDirectory);
        if (tblDirectory.getColumnModel().getColumnCount() > 0) {
            tblDirectory.getColumnModel().getColumn(0).setResizable(false);
        }

        backBtn.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        backBtn.setText("Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        txtView.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        txtView.setText("View and Update");
        txtView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtViewActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(DeleteAirline)
                            .addComponent(backBtn)
                            .addComponent(txtView))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(378, 378, 378)
                .addComponent(jLabel1)
                .addContainerGap(447, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(101, 101, 101)
                .addComponent(DeleteAirline)
                .addGap(64, 64, 64)
                .addComponent(backBtn)
                .addGap(56, 56, 56)
                .addComponent(txtView)
                .addContainerGap(237, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void DeleteAirlineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteAirlineActionPerformed
        // TODO add your handling code here:

        int selectedRow = tblDirectory.getSelectedRow();
    if(selectedRow>=0){
            int selectionButton = JOptionPane.YES_NO_OPTION;
            int selectionResult = JOptionPane.showConfirmDialog(null, "Are you sure to delete??","Warning",selectionButton);
            if(selectionResult == JOptionPane.YES_OPTION){
                Airliner airliner = (Airliner)tblDirectory.getValueAt(selectedRow, 0);
                airDir.deleteProduct(airliner);
                populateTable();
            }
        }else{
            JOptionPane.showMessageDialog(null, "Please select a Row!!");
        }
    }//GEN-LAST:event_DeleteAirlineActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        userProcesContainer.remove(this);
        CardLayout layout = (CardLayout)userProcesContainer.getLayout();
        layout.previous(userProcesContainer);
    }//GEN-LAST:event_backBtnActionPerformed

    private void txtViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtViewActionPerformed
        // TODO add your handling code here:
        
        int selectedRow = tblDirectory.getSelectedRow();
          if(selectedRow>=0)
        {
           Airliner a = (Airliner)tblDirectory.getValueAt(selectedRow, 0);
       
          //FlightSchedule flightschedule = (FlightSchedule) tblDirectory.getValueAt(selectedRow, 0);
            ViewFlightScheduleJPanel view = new ViewFlightScheduleJPanel(userProcesContainer , travelagency , airDir);
            userProcesContainer.add("viewPanel" , view);
            CardLayout layout = (CardLayout)userProcesContainer.getLayout();
            layout.next(userProcesContainer);
        }
          else
          {
              JOptionPane.showMessageDialog(null, "Please select a row");
          }
    
        
    }//GEN-LAST:event_txtViewActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton DeleteAirline;
    private javax.swing.JButton backBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblDirectory;
    private javax.swing.JButton txtView;
    // End of variables declaration//GEN-END:variables
}
