/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.ManageCustomers;

import Buisness.Airliner;
import Buisness.AirlinerDirectory;
import Buisness.Customer;
import Buisness.CustomerDirectory;
import Buisness.FlightSchedule;
import Buisness.FlightScheduleDirectory;
import UserInterface.ManageAirliners.TravelJPanel;
import java.awt.CardLayout;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author gadep
 */
public class BookingJPanel extends javax.swing.JPanel {

    /**
     * Creates new form BookingJPanel
     */
    private Airliner travelagency;
    private AirlinerDirectory airDir;
    private JPanel userProcesContainer ;
    private FlightScheduleDirectory flightdir;
    private Customer customer;
    private CustomerDirectory custdir;
    private FlightSchedule flightschedule;
    
    static List <Integer> seat;
    int seatCount = 0;
    double price;
    
    
    public BookingJPanel(JPanel userProcesContainer, Airliner travelagency , AirlinerDirectory airDir) {
        initComponents();
        this.userProcesContainer = userProcesContainer;
        this.travelagency = travelagency;
        this.flightschedule = new FlightSchedule();
       // this.airDir = airDir;
       // this.customer = customer;
       // this.custdir  = custdir;
        seat = new ArrayList<Integer>();
        populate();
    }
    
    public void populate()
    {
        price = Math.round(Math.random()*100000);
        priceTxt.setText(String.valueOf(price));
        
    
       seatCount = flightschedule.getSeat();
        for(int i=0 ;i<seatCount ;i++)
        {
            seat.add(i+1);
            comboBox.addItem(i+1);
        }
    }
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jPopupMenu2 = new javax.swing.JPopupMenu();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        btnBook = new javax.swing.JButton();
        backbtn = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        priceTxt = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        comboBox = new javax.swing.JComboBox();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("Customer Details");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(374, 34, -1, -1));

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(426, 101, 106, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 19)); // NOI18N
        jLabel2.setText("First Name");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(81, 104, -1, -1));
        add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(426, 141, 106, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 19)); // NOI18N
        jLabel3.setText("Last Name");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(81, 144, -1, -1));
        add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(426, 188, 106, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 19)); // NOI18N
        jLabel4.setText("Age");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(81, 191, 88, -1));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 19)); // NOI18N
        jLabel5.setText("Email Id");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(81, 231, 88, -1));
        add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(426, 228, 106, -1));

        btnBook.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btnBook.setText("Book");
        btnBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBookActionPerformed(evt);
            }
        });
        add(btnBook, new org.netbeans.lib.awtextra.AbsoluteConstraints(277, 406, -1, -1));

        backbtn.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        backbtn.setText("Back");
        backbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backbtnActionPerformed(evt);
            }
        });
        add(backbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(81, 460, -1, -1));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 19)); // NOI18N
        jLabel6.setText("Price");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(81, 285, -1, -1));
        add(priceTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(426, 282, 106, -1));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 19)); // NOI18N
        jLabel7.setText("Seat");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(81, 329, -1, -1));

        comboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2 ", "3", "4 ", "5 ", "6 ", "7 ", "8 ", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30" }));
        add(comboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(426, 329, 230, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void backbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbtnActionPerformed
        // TODO add your handling code here:
        userProcesContainer.remove(this);
        CardLayout layout = (CardLayout)userProcesContainer.getLayout();
        layout.previous(userProcesContainer);
    }//GEN-LAST:event_backbtnActionPerformed

    private void btnBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBookActionPerformed
        // TODO add your handling code here:
        
        if(jTextField1.getText().isEmpty() || jTextField2.getText().isEmpty()|| jTextField3.getText().isEmpty() || jTextField4.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(null , "Please add all the Mandatory fields!!");
        }
           try
           {
        
            Integer.parseInt(jTextField3.getText());
            
            if (Integer.parseInt(jTextField3.getText()) == 100 || Integer.parseInt(jTextField3.getText()) > 100)
            {
                JOptionPane.showMessageDialog(null , "Please enter correct age only");
                 return;
            } 
            
          /*  else {
                 Integer.parseInt(jTextField3.getText());
                
            }*/
          
           }
           catch(NumberFormatException e)
           {
               JOptionPane.showMessageDialog(null , "Please enter numeric values only"); 
             //  jTextField1.setText("");
              //  jTextField2.setText("");
                jTextField3.setText("");
               return;
           }
            CustomerDirectory custdir = new CustomerDirectory();
            Customer customer = new Customer();
             customer = custdir.addProduct();
            customer.setFirstName(jTextField1.getText());
            customer.setLastName(jTextField2.getText());
            customer.setAge(Integer.parseInt(jTextField3.getText()));
            customer.setEmailid(jTextField4.getText());
            
            int selectionButton = JOptionPane.YES_NO_OPTION;
            selectionButton = JOptionPane.showConfirmDialog(null, "Seat is reserved , Congratulations! You are redirected to Confirm Booking page !! ");
            seat.remove((comboBox.getSelectedItem()));
            comboBox.removeItemAt(comboBox.getSelectedIndex());
            btnBook.setEnabled(false);
            if(selectionButton ==JOptionPane.YES_OPTION)
            {
        //Confirmation con = new Confirmation(comboBox.getSelectedIndex()+2 ,userProcesContainer , customer , flightschedule , price);
        ConfirmationJPanel amPanel = new ConfirmationJPanel(comboBox.getSelectedIndex()+2,userProcesContainer , customer , flightschedule , price);
        userProcesContainer.add("TravelJPanel" ,amPanel );
        CardLayout layout = (CardLayout)userProcesContainer.getLayout();
        layout.next(userProcesContainer);
         
            }
            
            
            
           // prod.setDescription(txtDescription.getText());
           
            JOptionPane.showMessageDialog(null, "Booking Created Successfully");
           /* txtAirlineName.setText("");
            txtAirlineType.setText("");
            txtSeatCapacity.setText("");*/
            //txtDescription.setText("");
    }//GEN-LAST:event_btnBookActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backbtn;
    private javax.swing.JButton btnBook;
    private javax.swing.JComboBox comboBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JPopupMenu jPopupMenu2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField priceTxt;
    // End of variables declaration//GEN-END:variables
}
