/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.ManageCustomers;

import Buisness.Airliner;
import Buisness.AirlinerDirectory;
import Buisness.Customer;
import Buisness.CustomerDirectory;
import Buisness.FlightSchedule;
import Buisness.FlightScheduleDirectory;
import UserIterface.AirlinesManageFlightSchedule.CreateScheduleJPanel;
import java.awt.CardLayout;
import javax.print.attribute.standard.Destination;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
import javax.xml.transform.Source;

/**
 *
 * @author gadep
 */
public class CreateTravelJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateJPanel
     */
    String Source;
    String Destination;
    private Airliner travelagency;
    private AirlinerDirectory airDir;
    private JPanel userProcesContainer ;
    private FlightScheduleDirectory fliDir;
    private Customer customer;
    private CustomerDirectory custdir;
    private FlightSchedule flightschedule;
    
    public CreateTravelJPanel(JPanel userProcesContainer, Airliner travelagency, AirlinerDirectory airDir,FlightScheduleDirectory fliDir,FlightSchedule flightschedule ) {
        initComponents();
        this.userProcesContainer = userProcesContainer;
        this.travelagency = travelagency;
        this.airDir = airDir;
        this.Source = Source;
        this.fliDir = fliDir;
        this.Destination = Destination;
       // this.customer = customer;
        populateTable();    
    }

    public void populateTable()
    {
        DefaultTableModel dtm =  (DefaultTableModel)tblDirectory.getModel();
        dtm.setRowCount(0);
       for(Airliner a : airDir.getProductDirectory()){
          {
               for(FlightSchedule ars: a.getFlightScheduleDirectory().getSDListS())
            {
           Object row[] = new Object[dtm.getColumnCount()]; 
           row[0] = a;
           row[1] = a.getAirlineType();
           row[2] = a.getSeatCapacity();
           
                
           row[3] = ars.getFrom();
           row[4] = ars.getTo();
           row[5] = ars.getDateofJourney();
           row[6] = ars.getDepartureTime();
           row[7] = ars.getArrivalTime();
          
           dtm.addRow(row);
           
        }
          }

    }
    }
  /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        txtsourcre = new javax.swing.JTextField();
        txtdestination = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDirectory = new javax.swing.JTable();
        backbtn = new javax.swing.JButton();
        btnBook = new javax.swing.JButton();

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 19)); // NOI18N
        jButton1.setText("Source");

        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 19)); // NOI18N
        jButton2.setText("Destination");

        txtdestination.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdestinationActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jButton3.setText("Search");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        tblDirectory.setFont(new java.awt.Font("Times New Roman", 1, 19)); // NOI18N
        tblDirectory.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Airline Name", "Airline Type", "Flight Number", "From", "To", "DateofJourney", "DepartureTime", "ArrivalTime"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblDirectory);

        backbtn.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        backbtn.setText("Back");
        backbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backbtnActionPerformed(evt);
            }
        });

        btnBook.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btnBook.setText("Book");
        btnBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBookActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(118, 118, 118)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(87, 87, 87)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtdestination, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtsourcre, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(236, 236, 236)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(101, 101, 101)
                        .addComponent(btnBook))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(backbtn))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1013, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(59, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1)
                    .addComponent(txtsourcre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(txtdestination, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBook))
                .addGap(31, 31, 31)
                .addComponent(backbtn)
                .addContainerGap(133, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtdestinationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdestinationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdestinationActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
       
           String searchProduct = txtsourcre.getText();
           String searchProducts = txtdestination.getText();
           final  TableRowSorter<TableModel> sorter = new TableRowSorter (tblDirectory.getModel());
           tblDirectory.setRowSorter(sorter);
           
            if(searchProduct.length() == 0 && searchProducts.length() == 0)
            {
                sorter.setRowFilter(null);
                JOptionPane.showConfirmDialog(null,"Please enter Source and Destination values" , "Information" , JOptionPane.CANCEL_OPTION);
                
            }
            
            else
            {
                sorter.setRowFilter(RowFilter.regexFilter(searchProduct));
                sorter.setRowFilter(RowFilter.regexFilter(searchProducts));
            }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void backbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbtnActionPerformed
        // TODO add your handling code here:
        userProcesContainer.remove(this);
        CardLayout layout = (CardLayout)userProcesContainer.getLayout();
        layout.previous(userProcesContainer);
    }//GEN-LAST:event_backbtnActionPerformed

    private void btnBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBookActionPerformed
        // TODO add your handling code here:
         int selectedRow = tblDirectory.getSelectedRow();
          if(selectedRow<0)
        {
            JOptionPane.showConfirmDialog(null,"Please select a row to view details" , "Information" , JOptionPane.CANCEL_OPTION);
        }
          else{
            Airliner airliner = (Airliner) tblDirectory.getValueAt(selectedRow, 0);
        
        BookingJPanel mpcjp = new BookingJPanel(userProcesContainer , travelagency , airDir );
        userProcesContainer.add("CustomerDetails",mpcjp);
        CardLayout layout = (CardLayout)userProcesContainer.getLayout();
        layout.next(userProcesContainer);
          }
    }//GEN-LAST:event_btnBookActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backbtn;
    private javax.swing.JButton btnBook;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblDirectory;
    private javax.swing.JTextField txtdestination;
    private javax.swing.JTextField txtsourcre;
    // End of variables declaration//GEN-END:variables
}
